# Site settings
title: 观一中校友会  #左上角标题
SEOTitle: 观一中校友会  #tab标题
header-img: img/schoolPic9.jpg
email: 3060242196@qq.com
description: "观一中校友会3"
keyword: "观一中校友会4"
url: "https://gyzxyh.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
#github_repo: "https://github.com/liweimin1996/liweimin1996.github.io.git" # you code repository

# Sidebar settings
sidebar: true                  # whether or not using Sidebar.
sidebar-about-description: "QQ总群：258927439"  # 左侧滑栏介绍
sidebar-avatar: /img/school_icon.jpg      # 左侧滑栏头像 use absolute URL, seeing it's used in both `/` and `/about/`



#SNS settings
#RSS: false
#weibo_username:     CyberpunkV
#zhihu_username:     lixiaoyao233
#github_username:    liweimin1996
#twitter_username:   liweimin1996
#qq_username:     258927439




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: liweimin1996

# Gitalk
#gitalk:
#  enable: false    #是否开启Gitalk评论
#  clientID: 8bf9f6dcfa9638136442                           #生成的clientID
#  clientSecret: 4bb9a7fc7918372afe9ffa0a16530a53db2ddf16    #生成的clientSecret
#  repo: liweimin1996.github.io    #仓库名称
#  owner: liweimin1996    #github用户名
#  admin: liweimin1996
#  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: liweimin1996.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
#featured-tags: true                     # 是否使用首页标签
#featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#   {
#       title: "异绮帖",
#       href: "https://akinokaede.com/"
#   },
#   {
#       title: "Apple",
#        href: "https://apple.com"
#    }
#]
